# ------------------ Frontend Deployment ------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-frontend
  namespace: python-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-frontend
  template:
    metadata:
      labels:
        app: node-frontend
    spec:
      containers:
        - name: node-frontend
          image: docker.io/93750/mynodepython:latest
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: "http://backend-service:5000"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---

# ------------------ Frontend Service ------------------
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: python-node
spec:
  selector:
    app: node-frontend
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080   # Optional, for external access
  type: NodePort
